// app/api/subscription/export/route.ts - 历史记录导出API
import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth/auth";

// 强制动态渲染，因为使用了request.headers
export const dynamic = 'force-dynamic';
import { canExportData, getUserRecommendationHistory } from "@/lib/subscription/usage-tracker";

// PDF生成函数
async function generatePDF(history: { data: any[]; total: number; retentionDays: number }) {
  // 动态导入pdfmake
  const PdfPrinter = require('pdfmake');

  // 定义字体 - 使用内置字体
  const fonts = {
    Roboto: {
      normal: 'Helvetica',
      bold: 'Helvetica-Bold',
      italics: 'Helvetica-Oblique',
      bolditalics: 'Helvetica-BoldOblique'
    }
  };

  const printer = new PdfPrinter(fonts);

  // 构建表格数据
  const tableBody: any[][] = [
    // 表头
    [
      { text: 'Date', style: 'tableHeader' },
      { text: 'Category', style: 'tableHeader' },
      { text: 'Recommendation', style: 'tableHeader' },
    ]
  ];

  // 添加数据行
  for (const item of history.data) {
    const recommendation = item.recommendation as Record<string, unknown>;
    const category = (recommendation?.category as string) || 'N/A';

    // 提取推荐内容
    let content = '';
    if (recommendation?.content) {
      if (typeof recommendation.content === 'string') {
        content = recommendation.content;
      } else if (typeof recommendation.content === 'object') {
        const contentObj = recommendation.content as Record<string, unknown>;
        content = String(contentObj.title || contentObj.name || JSON.stringify(contentObj));
      }
    } else if (recommendation?.title) {
      content = recommendation.title as string;
    } else if (recommendation?.name) {
      content = recommendation.name as string;
    } else {
      content = JSON.stringify(recommendation).substring(0, 100) + '...';
    }

    // 截断过长的内容
    if (content.length > 150) {
      content = content.substring(0, 147) + '...';
    }

    const date = new Date(item.created_at).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });

    tableBody.push([
      { text: date, style: 'tableCell' },
      { text: category, style: 'tableCell' },
      { text: content, style: 'tableCell' },
    ]);
  }

  // 定义PDF文档
  const docDefinition: any = {
    content: [
      {
        text: 'Recommendation History Export',
        style: 'header',
        alignment: 'center',
        margin: [0, 0, 0, 20]
      },
      {
        text: `Exported on: ${new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        })}`,
        style: 'subheader',
        alignment: 'center',
        margin: [0, 0, 0, 10]
      },
      {
        text: `Total Records: ${history.total} | Retention: ${history.retentionDays} days`,
        style: 'info',
        alignment: 'center',
        margin: [0, 0, 0, 20]
      },
      {
        table: {
          headerRows: 1,
          widths: ['auto', 'auto', '*'],
          body: tableBody
        },
        layout: {
          fillColor: function(rowIndex: number) {
            return (rowIndex === 0) ? '#4F46E5' : (rowIndex % 2 === 0) ? '#F3F4F6' : null;
          },
          hLineWidth: function() { return 0.5; },
          vLineWidth: function() { return 0.5; },
          hLineColor: function() { return '#E5E7EB'; },
          vLineColor: function() { return '#E5E7EB'; },
          paddingLeft: function() { return 8; },
          paddingRight: function() { return 8; },
          paddingTop: function() { return 6; },
          paddingBottom: function() { return 6; },
        }
      },
      {
        text: '\n\nGenerated by RandomLife - Your Personal Discovery Platform',
        style: 'footer',
        alignment: 'center',
        margin: [0, 30, 0, 0]
      }
    ],
    styles: {
      header: {
        fontSize: 22,
        bold: true,
        color: '#1F2937'
      },
      subheader: {
        fontSize: 12,
        color: '#6B7280'
      },
      info: {
        fontSize: 10,
        color: '#9CA3AF'
      },
      tableHeader: {
        bold: true,
        fontSize: 11,
        color: 'white'
      },
      tableCell: {
        fontSize: 10,
        color: '#374151'
      },
      footer: {
        fontSize: 9,
        color: '#9CA3AF',
        italics: true
      }
    },
    defaultStyle: {
      font: 'Roboto'
    },
    pageSize: 'A4',
    pageMargins: [40, 60, 40, 60]
  };

  // 生成PDF Buffer
  return new Promise<Buffer>((resolve, reject) => {
    try {
      const pdfDoc = printer.createPdfKitDocument(docDefinition);
      const chunks: Buffer[] = [];

      pdfDoc.on('data', (chunk: Buffer) => {
        chunks.push(chunk);
      });

      pdfDoc.on('end', () => {
        const result = Buffer.concat(chunks);
        resolve(result);
      });

      pdfDoc.on('error', (err: Error) => {
        reject(err);
      });

      pdfDoc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * GET /api/subscription/export
 * 导出推荐历史记录
 */
export async function GET(request: NextRequest) {
  try {
    const authResult = await requireAuth(request);
    if (!authResult) {
      return NextResponse.json(
        { success: false, error: "Unauthorized" },
        { status: 401 }
      );
    }

    const { user } = authResult;
    const userId = user.id;

    // 检查导出权限
    const exportPermission = await canExportData(userId);
    if (!exportPermission.allowed) {
      return NextResponse.json(
        {
          success: false,
          error: exportPermission.reason,
          upgradeRequired: true,
        },
        { status: 403 }
      );
    }

    // 获取导出格式
    const searchParams = request.nextUrl.searchParams;
    const format = searchParams.get("format") || "json";

    // 验证格式是否支持
    if (!exportPermission.formats.includes(format)) {
      return NextResponse.json(
        {
          success: false,
          error: `Format '${format}' is not supported. Available formats: ${exportPermission.formats.join(", ")}`,
        },
        { status: 400 }
      );
    }

    // 获取历史记录
    const history = await getUserRecommendationHistory(userId, { limit: 1000 });

    if (format === "json") {
      return NextResponse.json({
        success: true,
        data: history.data,
        total: history.total,
        retentionDays: history.retentionDays,
        exportedAt: new Date().toISOString(),
      });
    }

    if (format === "csv") {
      // 生成CSV
      const csvRows: string[] = [];

      // 添加标题行
      csvRows.push("ID,Category,Recommendation,Created At");

      // 添加数据行
      for (const item of history.data) {
        const recommendation = item.recommendation as Record<string, unknown>;
        const csvRow = [
          item.id,
          (recommendation?.category as string) || "",
          JSON.stringify(recommendation?.content || recommendation).replace(/"/g, '""'),
          item.created_at,
        ]
          .map((field) => `"${field}"`)
          .join(",");
        csvRows.push(csvRow);
      }

      const csvContent = csvRows.join("\n");

      return new NextResponse(csvContent, {
        headers: {
          "Content-Type": "text/csv",
          "Content-Disposition": `attachment; filename="recommendations_${new Date().toISOString().split("T")[0]}.csv"`,
        },
      });
    }

    // PDF 格式
    if (format === "pdf") {
      try {
        const pdfBuffer = await generatePDF(history);

        return new NextResponse(new Uint8Array(pdfBuffer), {
          headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": `attachment; filename="recommendations_${new Date().toISOString().split("T")[0]}.pdf"`,
            "Content-Length": pdfBuffer.length.toString(),
          },
        });
      } catch (pdfError) {
        console.error("PDF generation error:", pdfError);
        return NextResponse.json(
          {
            success: false,
            error: "Failed to generate PDF. Please try JSON or CSV format.",
          },
          { status: 500 }
        );
      }
    }

    return NextResponse.json(
      { success: false, error: "Unknown format" },
      { status: 400 }
    );
  } catch (error) {
    console.error("Error exporting data:", error);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}
