// app/api/subscription/export/route.ts - 历史记录导出API
import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth/auth";
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

// 强制动态渲染，因为使用了request.headers
export const dynamic = 'force-dynamic';
import { canExportData, getUserRecommendationHistory } from "@/lib/subscription/usage-tracker";

// PDF生成函数 - 使用pdf-lib（纯JavaScript，无需文件系统访问）
async function generatePDF(history: { data: any[]; total: number; retentionDays: number }) {
  console.log('[PDF Export] Starting PDF generation with pdf-lib...');
  console.log('[PDF Export] History data count:', history.data.length);

  // 创建PDF文档
  const pdfDoc = await PDFDocument.create();

  // 加载标准字体
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

  // 页面设置
  const pageWidth = 595; // A4 width in points
  const pageHeight = 842; // A4 height in points
  const margin = 50;
  const contentWidth = pageWidth - 2 * margin;

  // 颜色定义
  const headerColor = rgb(0.31, 0.27, 0.9); // #4F46E5
  const textColor = rgb(0.22, 0.25, 0.31); // #374151
  const grayColor = rgb(0.42, 0.45, 0.51); // #6B7280
  const lightGray = rgb(0.95, 0.95, 0.96); // #F3F4F6

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPosition = pageHeight - margin;

  // 绘制标题
  const title = 'Recommendation History Export';
  const titleWidth = helveticaBold.widthOfTextAtSize(title, 22);
  page.drawText(title, {
    x: (pageWidth - titleWidth) / 2,
    y: yPosition,
    size: 22,
    font: helveticaBold,
    color: textColor,
  });
  yPosition -= 30;

  // 绘制导出时间
  const exportDate = `Exported on: ${new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })}`;
  const exportDateWidth = helvetica.widthOfTextAtSize(exportDate, 12);
  page.drawText(exportDate, {
    x: (pageWidth - exportDateWidth) / 2,
    y: yPosition,
    size: 12,
    font: helvetica,
    color: grayColor,
  });
  yPosition -= 20;

  // 绘制统计信息
  const stats = `Total Records: ${history.total} | Retention: ${history.retentionDays} days`;
  const statsWidth = helvetica.widthOfTextAtSize(stats, 10);
  page.drawText(stats, {
    x: (pageWidth - statsWidth) / 2,
    y: yPosition,
    size: 10,
    font: helvetica,
    color: grayColor,
  });
  yPosition -= 40;

  // 表格设置
  const colWidths = [80, 100, contentWidth - 180]; // Date, Category, Recommendation
  const rowHeight = 25;
  const cellPadding = 5;

  // 绘制表头
  const headerY = yPosition;
  page.drawRectangle({
    x: margin,
    y: headerY - rowHeight,
    width: contentWidth,
    height: rowHeight,
    color: headerColor,
  });

  // 表头文字
  const headers = ['Date', 'Category', 'Recommendation'];
  let xPos = margin + cellPadding;
  for (let i = 0; i < headers.length; i++) {
    page.drawText(headers[i], {
      x: xPos,
      y: headerY - rowHeight + 8,
      size: 11,
      font: helveticaBold,
      color: rgb(1, 1, 1), // white
    });
    xPos += colWidths[i];
  }
  yPosition = headerY - rowHeight;

  // 绘制数据行
  for (let rowIndex = 0; rowIndex < history.data.length; rowIndex++) {
    const item = history.data[rowIndex];
    const recommendation = item.recommendation as Record<string, unknown>;

    // 检查是否需要新页面
    if (yPosition - rowHeight < margin + 50) {
      // 添加页脚
      const footer = 'Generated by RandomLife - Your Personal Discovery Platform';
      const footerWidth = helvetica.widthOfTextAtSize(footer, 9);
      page.drawText(footer, {
        x: (pageWidth - footerWidth) / 2,
        y: margin / 2,
        size: 9,
        font: helvetica,
        color: grayColor,
      });

      // 添加新页面
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - margin;
    }

    // 交替行背景色
    if (rowIndex % 2 === 0) {
      page.drawRectangle({
        x: margin,
        y: yPosition - rowHeight,
        width: contentWidth,
        height: rowHeight,
        color: lightGray,
      });
    }

    // 提取数据
    const date = new Date(item.created_at).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
    const category = (recommendation?.category as string) || 'N/A';

    let content = '';
    if (recommendation?.title) {
      content = recommendation.title as string;
    } else if (recommendation?.content) {
      content = String(recommendation.content);
    } else {
      content = 'N/A';
    }

    // 截断过长内容
    const maxContentLength = 50;
    if (content.length > maxContentLength) {
      content = content.substring(0, maxContentLength - 3) + '...';
    }

    // 绘制单元格内容
    xPos = margin + cellPadding;
    const rowData = [date, category, content];

    for (let i = 0; i < rowData.length; i++) {
      // 截断文本以适应列宽
      let text = rowData[i];
      const maxWidth = colWidths[i] - cellPadding * 2;
      while (helvetica.widthOfTextAtSize(text, 10) > maxWidth && text.length > 3) {
        text = text.substring(0, text.length - 4) + '...';
      }

      page.drawText(text, {
        x: xPos,
        y: yPosition - rowHeight + 8,
        size: 10,
        font: helvetica,
        color: textColor,
      });
      xPos += colWidths[i];
    }

    yPosition -= rowHeight;
  }

  // 添加最后的页脚
  const footer = 'Generated by RandomLife - Your Personal Discovery Platform';
  const footerWidth = helvetica.widthOfTextAtSize(footer, 9);
  page.drawText(footer, {
    x: (pageWidth - footerWidth) / 2,
    y: margin / 2,
    size: 9,
    font: helvetica,
    color: grayColor,
  });

  console.log('[PDF Export] PDF document created, saving...');

  // 保存PDF
  const pdfBytes = await pdfDoc.save();

  console.log('[PDF Export] PDF generation completed, size:', pdfBytes.length);

  return Buffer.from(pdfBytes);
}

/**
 * GET /api/subscription/export
 * 导出推荐历史记录
 */
export async function GET(request: NextRequest) {
  try {
    const authResult = await requireAuth(request);
    if (!authResult) {
      return NextResponse.json(
        { success: false, error: "Unauthorized" },
        { status: 401 }
      );
    }

    const { user } = authResult;
    const userId = user.id;

    // 检查导出权限
    const exportPermission = await canExportData(userId);
    if (!exportPermission.allowed) {
      return NextResponse.json(
        {
          success: false,
          error: exportPermission.reason,
          upgradeRequired: true,
        },
        { status: 403 }
      );
    }

    // 获取导出格式
    const searchParams = request.nextUrl.searchParams;
    const format = searchParams.get("format") || "json";

    // 验证格式是否支持
    if (!exportPermission.formats.includes(format)) {
      return NextResponse.json(
        {
          success: false,
          error: `Format '${format}' is not supported. Available formats: ${exportPermission.formats.join(", ")}`,
        },
        { status: 400 }
      );
    }

    // 获取历史记录
    console.log(`[Export API] Fetching history for user ${userId}, format: ${format}`);
    const history = await getUserRecommendationHistory(userId, { limit: 1000 });
    console.log(`[Export API] History fetched: ${history.total} records, ${history.data.length} data items`);

    if (format === "json") {
      return NextResponse.json({
        success: true,
        data: history.data,
        total: history.total,
        retentionDays: history.retentionDays,
        exportedAt: new Date().toISOString(),
      });
    }

    if (format === "csv") {
      // 生成CSV
      const csvRows: string[] = [];

      // 添加标题行
      csvRows.push("ID,Category,Recommendation,Created At");

      // 添加数据行
      for (const item of history.data) {
        const recommendation = item.recommendation as Record<string, unknown>;
        const csvRow = [
          item.id,
          (recommendation?.category as string) || "",
          JSON.stringify(recommendation?.content || recommendation).replace(/"/g, '""'),
          item.created_at,
        ]
          .map((field) => `"${field}"`)
          .join(",");
        csvRows.push(csvRow);
      }

      const csvContent = csvRows.join("\n");

      return new NextResponse(csvContent, {
        headers: {
          "Content-Type": "text/csv",
          "Content-Disposition": `attachment; filename="recommendations_${new Date().toISOString().split("T")[0]}.csv"`,
        },
      });
    }

    // PDF 格式
    if (format === "pdf") {
      try {
        console.log('[Export API] Starting PDF generation...');
        const pdfBuffer = await generatePDF(history);
        console.log('[Export API] PDF generated successfully, size:', pdfBuffer.length);

        return new NextResponse(new Uint8Array(pdfBuffer), {
          headers: {
            "Content-Type": "application/pdf",
            "Content-Disposition": `attachment; filename="recommendations_${new Date().toISOString().split("T")[0]}.pdf"`,
            "Content-Length": pdfBuffer.length.toString(),
          },
        });
      } catch (pdfError: any) {
        console.error("[Export API] PDF generation error:", {
          message: pdfError?.message,
          stack: pdfError?.stack,
          error: pdfError
        });
        return NextResponse.json(
          {
            success: false,
            error: `Failed to generate PDF: ${pdfError?.message || 'Unknown error'}`,
            details: pdfError?.stack
          },
          { status: 500 }
        );
      }
    }

    return NextResponse.json(
      { success: false, error: "Unknown format" },
      { status: 400 }
    );
  } catch (error) {
    console.error("Error exporting data:", error);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}
